{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running on local URL:  http://127.0.0.1:7864\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\C00386\\Desktop\\JC\\Initiatives\\pdf-chatbot\\gradio_chat.ipynb Cell 1\u001b[0m line \u001b[0;36m1\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/C00386/Desktop/JC/Initiatives/pdf-chatbot/gradio_chat.ipynb#W3sZmlsZQ%3D%3D?line=7'>8</a>\u001b[0m demo \u001b[39m=\u001b[39m gr\u001b[39m.\u001b[39mInterface(fn\u001b[39m=\u001b[39mgreet, inputs\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mtext\u001b[39m\u001b[39m\"\u001b[39m, outputs\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mtext\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/C00386/Desktop/JC/Initiatives/pdf-chatbot/gradio_chat.ipynb#W3sZmlsZQ%3D%3D?line=9'>10</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39m__name__\u001b[39m \u001b[39m==\u001b[39m \u001b[39m\"\u001b[39m\u001b[39m__main__\u001b[39m\u001b[39m\"\u001b[39m:\n\u001b[1;32m---> <a href='vscode-notebook-cell:/c%3A/Users/C00386/Desktop/JC/Initiatives/pdf-chatbot/gradio_chat.ipynb#W3sZmlsZQ%3D%3D?line=10'>11</a>\u001b[0m     demo\u001b[39m.\u001b[39;49mlaunch(show_api\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m)   \n",
      "File \u001b[1;32mc:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\blocks.py:2115\u001b[0m, in \u001b[0;36mBlocks.launch\u001b[1;34m(self, inline, inbrowser, share, debug, enable_queue, max_threads, auth, auth_message, prevent_thread_lock, show_error, server_name, server_port, show_tips, height, width, encrypt, favicon_path, ssl_keyfile, ssl_certfile, ssl_keyfile_password, ssl_verify, quiet, show_api, file_directories, allowed_paths, blocked_paths, root_path, _frontend, app_kwargs, state_session_capacity)\u001b[0m\n\u001b[0;32m   2107\u001b[0m \u001b[39m# If running in a colab or not able to access localhost,\u001b[39;00m\n\u001b[0;32m   2108\u001b[0m \u001b[39m# a shareable link must be created.\u001b[39;00m\n\u001b[0;32m   2109\u001b[0m \u001b[39mif\u001b[39;00m (\n\u001b[0;32m   2110\u001b[0m     _frontend\n\u001b[0;32m   2111\u001b[0m     \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m wasm_utils\u001b[39m.\u001b[39mIS_WASM\n\u001b[0;32m   2112\u001b[0m     \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m networking\u001b[39m.\u001b[39murl_ok(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mlocal_url)\n\u001b[0;32m   2113\u001b[0m     \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mshare\n\u001b[0;32m   2114\u001b[0m ):\n\u001b[1;32m-> 2115\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\n\u001b[0;32m   2116\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mWhen localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m   2117\u001b[0m     )\n\u001b[0;32m   2119\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mis_colab:\n\u001b[0;32m   2120\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m quiet:\n",
      "\u001b[1;31mValueError\u001b[0m: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost."
     ]
    }
   ],
   "source": [
    "import gradio as gr\n",
    "import os\n",
    "os.environ[\"no_proxy\"] = \"localhost,127.0.0.1,::1\"\n",
    "\n",
    "def greet(name):\n",
    "    return \"Hello \" + name + \"!\"\n",
    "\n",
    "demo = gr.Interface(fn=greet, inputs=\"text\", outputs=\"text\")\n",
    "    \n",
    "if __name__ == \"__main__\":\n",
    "    demo.launch(show_api=False)   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    }
   ],
   "source": [
    "import gradio as gr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running on local URL:  http://127.0.0.1:7862\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n",
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"http://127.0.0.1:7862/\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": []
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\protocols\\http\\httptools_impl.py\", line 435, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\uvicorn\\middleware\\proxy_headers.py\", line 78, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\applications.py\", line 276, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\applications.py\", line 122, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 184, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\errors.py\", line 162, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\cors.py\", line 84, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 79, in __call__\n",
      "    raise exc\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 68, in __call__\n",
      "    await self.app(scope, receive, sender)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 21, in __call__\n",
      "    raise e\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\middleware\\asyncexitstack.py\", line 18, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 718, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 276, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\routing.py\", line 66, in app\n",
      "    response = await func(request)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 237, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\fastapi\\routing.py\", line 165, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\starlette\\concurrency.py\", line 41, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\to_thread.py\", line 31, in run_sync\n",
      "    return await get_asynclib().run_sync_in_worker_thread(\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 937, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 867, in run\n",
      "    result = context.run(func, *args)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\routes.py\", line 322, in main\n",
      "    config[\"root\"] = route_utils.strip_url(root_path)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\gradio\\route_utils.py\", line 263, in strip_url\n",
      "    parsed_url = httpx.URL(orig_url)\n",
      "  File \"c:\\Users\\C00386\\Anaconda3\\envs\\chromadb\\lib\\site-packages\\httpx\\_models.py\", line 90, in __init__\n",
      "    raise InvalidURL(\"No scheme included in URL.\")\n",
      "httpx._exceptions.InvalidURL: No scheme included in URL.\n"
     ]
    }
   ],
   "source": [
    "def file_process(file_obj):\n",
    "    return file_obj\n",
    "\n",
    "demo = gr.Interface(\n",
    "    file_process,\n",
    "    gr.File(file_count=\"multiple\", file_types=[\"text\", \".pdf\"]),\n",
    "    \"text\",\n",
    ")\n",
    "demo.launch(share=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "chromadb",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
